<%@ page contentType="text/html;charset=UTF-8" language="java"%>
<html lang="en">
	<head>
		<title>IntelliQ.me - Imprint</title>
		<%@include file="../includes/en/common_head.jsp"%>
	</head>
	
	<body>
		<%@include file="../includes/en/common_navigation.jsp"%>
	
		<main>
	
		<div class="container">

			<h3>Imprint</h3>

			<div class="section">
	
				<div class="row">
					<div class="col s12 m12 l4">
						<h5>Provider Identification</h5>
						<p>
							IntelliQ.me UG (haftungsbeschränkt)<br/>
							Geschwister-Scholl-Str. 80<br/>
							14471 Potsdan<br/>
							Brandenburg, Germany
						</p>
					</div>

					<div class="col s12 m12 l4">
						<h5 class="hide-on-med-and-down">&nbsp;</h5>
						<p>
							Managing Director: <a href="https://steppschuh.net">Stephan Schultz</a><br/>
							Registration Court: Amtsgericht Potsdam<br/>
							Registration Number: HRB29427P<br/>
							VAT-ID: DE309275209
						</p>
					</div>

					<div class="col s12 m12 l4">
						<h5>Contact</h5>
						<p>
							Mail: <a href="mailto:mail@intelliq.me">mail@intelliq.me</a><br/>
							Social: <a href="https://www.facebook.com/Intelliq.me">Facebook</a>, <a href="https://twitter.com/IntelliQMe">Twitter</a><br/>
							Phone: +49 151 54854847
						</p>
					</div>
	
				</div>
	
			</div>

			<h3>Privacy Policy</h3>

			<div class="section">
	
				<div class="row">
					<div class="col s12">
						<h5>Privacy</h5>
						<p>
							The use of our website is usually possible without providing personal information. Any personal data (eg name or email address) are collected as far as possible on a voluntary basis. These data are not forwarded to third parties without your express consent. We point out that data transmission over the Internet (e.g. when communicating via email) can have security gaps. A complete protection of data against unauthorized access by third parties is impossible.
							<br/>
							The use of our contact details under the imprint by third parties for sending unsolicited advertisements and information materials is hereby expressly prohibited. The operators of these pages reserves the right to enter into legal steps in case of unsolicited promotional information, such as spam e-mails.
						</p>
					</div>
				</div>

				<div class="row">
					<div class="col s12">
						<h5>Google Analytics</h5>
						<p>
							This website uses Google Analytics, a web analytics service provided by Google Inc. (“Google”). Google Analytics uses Cookies, text files that are stored on your computer and enable the analysis of your use of the website. The information generated by the cookie about your use of this website is usually transferred to a server of Google in the US and stored there. In case of activation of IP anonymization on this website your IP address will be shortened from Google within Member States of the European Union or other parties to the Agreement on the European Economic Area.
							<br/>
							Only in exceptional cases will the full IP address be transmitted to a Google server in the US and shortened there. On behalf of the operator of this site Google will use this information to evaluate your use of the website, compiling reports on website activity and providing other related services to the website operator. The IP address transferred as part of Google Analytics will not be merged with other Google data.
							<br/>
							You may refuse the use of cookies by selecting the appropriate settings on your browser; but we point out that you possibly cannot use this website to its full extent. You can also prevent the data generation by the cookie the transfer of data relating to your usage of the website (incl. your IP address) to Google and the processing of these data by Google, by downloading and installing the following file available <a href="http://tools.google.com/dlpage/gaoptout" target="_blank">here</a>.
						</p>
					</div>
				</div>
	
			</div>

			<h3>Liability Disclaimer</h3>

			<div class="section">
	
				<div class="row">
					<div class="col s12">
						<h5>Liability for contents</h5>
						<p>
							The contents of our site have been compiled with the greatest care. However, we do not assume any liability for the correctness, completeness and timeliness of the contents. As a service provider, according to § 7 (1) TMG (German Telemedia Act) we are responsible for our own contents on these pages in accordance with general laws. According to §§ 8 to 10 TMG, we are not, however, obligated as a service provider to monitor transmitted or saved external information or to research circumstances which point to an illegal activity. Obligations for the removal or barring of the use of information in accordance with legal regulations remain unaffected. Any liability in this respect is, however, only incurred from the moment that knowledge of the specific breach of law is obtained. When we become aware of legal violations we will remove the content that is in violation of the law.
							<br/>
							The website contents and material on these websites/pages created by the website operators is subject to German copyright law. Copying, processing, distributing and any kind of use outside the limits of copyright law require the written approval of the respective author or creator. Downloads and copies of these websites/pages are only permitted for private use and are not permitted for commercial use. To the extent that the contents of this website were not created by the operator, third party copyrights are respected. In particular, contents of third parties are correspondingly marked. Should you still have reason to believe that a copyright violation has occurred, please notify us accordingly. When we become aware of legal violations we will immediately remove such contents.
						</p>
					</div>
				</div>

				<div class="row">
					<div class="col s12">
						<h5>Liability for links</h5>
						<p>
							Our site contains links to external websites and we do not have any influence on their contents. For that reason, we do not assume any liability for these external contents. The respective provider or operator of the websites is responsible for the contents of these linked pages and websites. The linked pages and websites were checked for potential illegal content at the time when the link was established. Unlawful contents were not apparent at the time of linking, however, a permanent control of the contents of the linked websites shall not be considered reasonable without a concrete indication for a violation of the law. When we become aware of legal violations we will immediately remove such links.
						</p>
					</div>
				</div>
	
			</div>

		</div>
	
		<div id="modal-contact" class="modal">
			<div class="modal-content">
				<h4>Contact</h4>
				<p>If you want to learn more about IntelliQ, please get in touch at any time. We will get back to you as soon as possible.</p>
	
				<div class="row">
					<form class="col s12">
						<div class="row">
							<div class="input-field col s6">
								<input id="contact_first_name" type="text" class=""> <label for="contact_first_name">First name</label>
							</div>
							<div class="input-field col s6">
								<input id="contact_last_name" type="text" class=""> <label for="contact_last_name">Last name</label>
							</div>
						</div>
						<div class="row">
							<div class="input-field col s12">
								<input id="contact_email" type="email" class=""> <label for="contact_email">Your e-mail address</label>
							</div>
						</div>
						<div class="row">
							<div class="input-field col s12">
								<textarea id="contact_message" class="materialize-textarea"></textarea>
								<label for="contact_message">Message</label>
							</div>
						</div>
					</form>
				</div>
	
			</div>
	
			<div class="modal-footer">
				<a href="javascript:submitContactForm();" class=" modal-action modal-close waves-effect waves-green btn-flat">Send</a>
			</div>
		</div>
	
		</main>
	
		<%@include file="../includes/en/common_footer.jsp"%>
	
	</body>
</html>
